[workspace]
resolver = "2"
members = [
    "crates/copi-core",
    "crates/copi-protocol",
    "crates/copi-mobile-binding",
    "crates/uniffi-bindgen",
]

exclude = ["firmware/pico", "firmware/pico2"]
